site_name: KODA TEXTBOOK FOR SEO
theme:
  name: material
  logo: images/koda_logo.svg
  favicon: images/koda_logo.svg
  palette:
    - scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: white
      accent: yellow
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      font:
        header: Rubik
        text: Source Code Variable
      custom_dir: docs
      extra_css:
        - extra.css



  features:
     - search.highlight
     - content.code.copy
     - content.tabs.link


  markdown_extensions:
    - def_list
    - sane_lists
    - pymdownx.tasklist:
        custom_checkbox: true
    - tables
    - pymdownx.superfences
    - pymdownx.tabbed:
          alternate_style: true




nav:
#  - Home: index.md
  - About This Book: about-this-book.md
  - What to expect?: what-to-expect.md
  - Curriculum: curriculum.md
#  - Fundamentals: fundamental.md
  - Week 1:
    - What is SEO?: week_1/week1day1.md
    - Search Engine: week_1/week1day2.md
    - Ahrefs: week_1/week1day3.md
    - Keyword Research: week_1/week1day4.md
    - Competitor Analysis & Keyword Strategy: week_1/week1day5.md
  - Week 2:
      - On-page SEO: week_2/week2day1.md
      - Write and Optimized a Content: week_2/week2day2.md
      - Image SEO (Alt Text, File Size, Naming Conventions): week_2/week2day3.md
      - Structure in Canva: week_2/week2day4.md
      - Making an Image Content: week_2/week2day5.md
  - Week 3:
      - URL Structure: week_3/week3day1.md
      - Website Branding Element: week_3/week3day2.md
      - Website Linking Strategies: week_3/week3day3.md
      - SEO Tracking & SEMrush: week_3/week3day4.md
      - Google Analytics & Console: week_3/week3day5.md




