site_name: KODA TEXTBOOK FOR SEO

theme:
  name: material
  logo: images/koda_logo.svg
  favicon: images/koda_logo.svg
  palette:
    - scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Rubik
    code: "Source Code Variable"
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy
    - content.tabs.link
    - content.tabs.tabs
    - content.code.annotate
    - content.tooltips
  icon:
    repo: fontawesome/brands/github
  language: en
  custom_dir: docs
  extra_css:
    - stylesheets/extra.css

  markdown_extensions:
    - def_list
    - sane_lists
    - pymdownx.tasklist:
        custom_checkbox: true
    - tables
    - pymdownx.superfences
    - pymdownx.tabbed:
          alternate_style: true
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - md_in_html
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - About This Book: about-this-book.md
  - What to expect?: what-to-expect.md
  - Curriculum: curriculum.md
  - Week 1:
    - Day 1: week_1/week1day1.md
#    - Day 2: week_1/week1day2.md
#    - Day 3: week_1/week1day3.md
#    - Day 4: week_1/week1day4.md
#    - Day 5: week_1/week1day5.md
#  - Week 2:
#    - Day 1: week_2/week2day1.md
#    - Day 2: week_2/week2day2.md
#    - Day 3: week_2/week2day3.md
#    - Day 4: week_2/week2day4.md
#    - Day 5: week_2/week2day5.md
#  - Week 3:
#    - Day 1: week_3/week3day1.md
#    - Day 2: week_3/week3day2.md
#    - Day 3: week_3/week3day3.md
#    - Day 4: week_3/week3day4.md
#    - Day 5: week_3/week3day5.md
#  - Week 4:
#    - Day 1: week_4/week4day1.md
#    - Day 2: week_4/week4day2.md
#    - Day 3: week_4/week4day3.md
#    - Day 4: week_4/week4day4.md
#    - Day 5: week_4/week4day5.md
#  - Week 5:
#    - Day 1: week_5/week5day1.md
#    - Day 2: week_5/week5day2.md
#    - Day 3: week_5/week5day3.md
#    - Day 4: week_5/week5day4.md
#    - Day 5: week_5/week5day5.md





