site_name: KODA TEXTBOOK FOR SEO
theme:
  name: material
  logo: images/koda_logo.svg
  favicon: images/koda_logo.svg
  palette:
    - scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: white
      accent: yellow
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      font:
        header: Rubik
        text: Source Code Variable
      custom_dir: docs
      extra_css:
        - extra.css



  features:
     - search.highlight
     - content.code.copy


  markdown_extensions:
    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true
    - tables


nav:
#  - Home: index.md
  - About This Book: about-this-book.md
  - What to expect?: what-to-expect.md
  - Curriculum: curriculum.md
#  - Fundamentals: fundamental.md
  - Week 1:
    - Day 1: week 1/week1day1.md
    - Day 2: week 1/week1day2.md
    - Day 3: week 1/week1day3.md
    - Day 4: week 1/week1day4.md
    - Day 5: week 1/week1day5.md


